# Generated by Django 4.0.6 on 2022-07-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joumientry',
            options={'verbose_name_plural': 'JoumiEntries'},
        ),
    ]
